version: "3.9"

services:
  # 1. 데이터베이스
  tm_db:
    image: postgres:16
    container_name: tm_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - tm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - tm_net

  # 2. 백엔드 (Django)
  tm_backend:
    build: ./backend
    container_name: tm_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - tm_media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      tm_db:
        condition: service_healthy
      tm_redis:
        condition: service_started
    env_file: .env
    environment:
      # ⚠️ 도커 내부에서는 'localhost' 대신 서비스명('tm_redis', 'tm_db')을 씁니다.
      - CELERY_BROKER_URL=redis://tm_redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tm_db
    networks:
      - tm_net

  # 3. Redis
  tm_redis:
    image: redis:7-alpine
    container_name: tm_redis
    command: [ "redis-server", "--appendonly", "no" ]
    volumes:
      - tm_redis_data:/data
    networks:
      - tm_net

  # 4. Celery Worker (일꾼)
  tm_celery_worker:
    build: ./backend
    container_name: tm_celery_worker
    # ⚠️ 'config'는 프로젝트 폴더명에 맞게 수정 필요
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
      - tm_media_data:/app/media
    env_file: .env
    environment:
      - CELERY_BROKER_URL=redis://tm_redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tm_db
    depends_on:
      - tm_db
      - tm_redis
    restart: unless-stopped
    networks:
      - tm_net

  # 5. Celery Beat (알람시계 - 스케줄러)
  tm_celery_beat:
    build: ./backend
    container_name: tm_celery_beat
    # 스케줄러 실행 명령어
    command: celery -A config beat --loglevel=info
    volumes:
      - ./backend:/app
    env_file: .env
    environment:
      - CELERY_BROKER_URL=redis://tm_redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tm_db
    depends_on:
      - tm_db
      - tm_redis
    restart: unless-stopped
    networks:
      - tm_net

volumes:
  tm_postgres_data:
  tm_redis_data:
  tm_media_data:

networks:
  tm_net:
    driver: bridge