# Generated by Django 6.0.1 on 2026-01-19 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('login_id', models.CharField(max_length=50, unique=True, verbose_name='로그인ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('role', models.CharField(choices=[('ADMIN', '총괄관리자'), ('MANAGER', '팀장'), ('AGENT', '상담원')], default='AGENT', max_length=20, verbose_name='권한')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('team_name', models.CharField(blank=True, max_length=50, verbose_name='소속팀')),
                ('extension_number', models.CharField(blank=True, max_length=10, verbose_name='내선번호')),
                ('daily_cap', models.IntegerField(default=50, verbose_name='일일 할당량')),
                ('total_assigned', models.IntegerField(default=0, verbose_name='누적 할당건수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='상담원 계정')),
            ],
            options={
                'db_table': 'agent_profiles',
            },
        ),
    ]
