# Generated by Django 6.0.1 on 2026-01-26 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('assigned_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('ADMIN', '관리자'), ('MANAGER', '매니저'), ('AGENT', '상담원')], default='AGENT', max_length=10)),
                ('status', models.CharField(choices=[('OFFLINE', '오프라인'), ('ONLINE', '온라인'), ('BREAK', '휴식중'), ('BUSY', '통화중')], default='OFFLINE', max_length=10)),
                ('daily_cap', models.IntegerField(default=50)),
                ('is_auto_assign', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tm_agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
