# Generated by Django 6.0.1 on 2026-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
