# Generated by Django 6.0.1 on 2026-01-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='team',
            field=models.CharField(blank=True, choices=[('BATTERY', '배터리'), ('MOBILITY', '모빌리티'), ('SOLAR', '태양광'), ('MACHINE', '산업기계')], max_length=20, null=True, verbose_name='소속 팀'),
        ),
    ]
