# Generated by Django 6.0.1 on 2026-01-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at'], 'verbose_name': '상담원 프로필'},
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='account',
            new_name='user',
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='개인 연락처'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='assigned_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='직통 번호'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='사원 번호'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='daily_cap',
            field=models.IntegerField(default=50, verbose_name='일일 할당량'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_auto_assign',
            field=models.BooleanField(default=True, verbose_name='자동 배정 여부'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='상담원 이름'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ADMIN', '관리자'), ('MANAGER', '매니저'), ('AGENT', '상담원')], default='AGENT', max_length=10, verbose_name='권한'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('OFFLINE', '오프라인'), ('ONLINE', '온라인'), ('BREAK', '휴식중'), ('BUSY', '통화중')], default='OFFLINE', max_length=10, verbose_name='현재 상태'),
        ),
    ]
