# Generated by Django 6.0.1 on 2026-01-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_options_rename_account_agent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='phone_number',
        ),
    ]
