# Generated by Django 6.0.1 on 2026-01-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
