# Generated by Django 6.0.1 on 2026-02-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('OFFLINE', '오프라인'), ('ONLINE', '온라인'), ('BREAK', '휴식중'), ('BUSY', '통화중'), ('RESIGNED', '퇴사')], default='OFFLINE', max_length=10, verbose_name='현재 상태'),
        ),
    ]
