# Generated by Django 6.0.1 on 2026-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='current_assigned',
            field=models.IntegerField(default=0, verbose_name='금일 배정 건수'),
        ),
    ]
