# Generated by Django 6.0.1 on 2026-02-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_current_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='current_assigned',
        ),
    ]
