# Generated by Django 6.0.1 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_remove_agent_current_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='team',
            field=models.CharField(blank=True, choices=[('SALES_1', '영업 1팀')], max_length=20, null=True, verbose_name='소속 팀'),
        ),
    ]
