# Generated by Django 6.0.1 on 2026-02-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agent_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='team',
            field=models.CharField(blank=True, choices=[('SALES_TM', '1차 TM팀'), ('SALES_MAIN', '2차 본영업팀')], max_length=20, null=True, verbose_name='소속 팀'),
        ),
    ]
