# Generated by Django 6.0.1 on 2026-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='관리자', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
