# Generated by Django 6.0.1 on 2026-01-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='고객명')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='연락처')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='성별')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='지역')),
                ('status', models.CharField(choices=[('NEW', '접수(신규)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('SUCCESS', '성공(계약)'), ('LATER', '재통화'), ('INVALID', '결번/오류')], default='NEW', max_length=20, verbose_name='상담 상태')),
                ('memo', models.TextField(blank=True, default='', verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='DB 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='agents.agent', verbose_name='담당 상담원')),
            ],
            options={
                'verbose_name': '고객 DB',
                'db_table': 'tm_customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
