# Generated by Django 6.0.1 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAssignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='실행 시간')),
                ('total_assigned', models.IntegerField(default=0, verbose_name='배정된 수')),
                ('agent_count', models.IntegerField(default=0, verbose_name='참여 상담원 수')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILURE', '실패')], default='SUCCESS', max_length=10)),
                ('message', models.TextField(blank=True, null=True, verbose_name='결과 메시지/에러로그')),
            ],
            options={
                'verbose_name': '자동 배정 이력',
                'verbose_name_plural': '자동 배정 이력',
                'ordering': ['-executed_at'],
            },
        ),
    ]
