# Generated by Django 6.0.1 on 2026-02-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_autoassignlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='team',
            field=models.CharField(blank=True, choices=[('BATTERY', '배터리'), ('MOBILITY', '모빌리티'), ('SOLAR', '태양광'), ('MACHINE', '산업기계')], max_length=20, null=True, verbose_name='관심 분야(팀)'),
        ),
    ]
