# Generated by Django 6.0.1 on 2026-02-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='배정일시'),
        ),
    ]
