# Generated by Django 6.0.1 on 2026-02-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_assigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='실행 일시')),
                ('triggered_by', models.CharField(default='SYSTEM', max_length=50, verbose_name='실행자')),
                ('total_assigned', models.IntegerField(default=0, verbose_name='총 배정 건수')),
                ('agent_count', models.IntegerField(default=0, verbose_name='참여 상담원 수')),
                ('result_detail', models.JSONField(blank=True, default=dict, verbose_name='상세 배정 내역')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('PARTIAL_SUCCESS', '부분 성공'), ('FAILURE', '실패')], default='SUCCESS', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 로그')),
            ],
            options={
                'verbose_name': '자동 배정 이력',
                'verbose_name_plural': '자동 배정 이력',
                'db_table': 'tm_assignment_logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.DeleteModel(
            name='AutoAssignLog',
        ),
    ]
