# Generated by Django 6.0.1 on 2026-02-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_assignment_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='cust_stat_agent_team_ct',
        ),
        migrations.AddField(
            model_name='customer',
            name='category_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='분야1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='분야2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='분야3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지역1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지역2'),
        ),
    ]
