# Generated by Django 6.0.1 on 2026-02-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_customer_cust_stat_agent_team_ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='연락처'),
            preserve_default=False,
        ),
    ]
