# Generated by Django 6.0.1 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='team',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(
                fields=['status', 'assigned_agent', 'created_at'],
                name='cust_stat_agent_ct',
            ),
        ),
    ]
