# Generated by Django 6.0.1 on 2026-02-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_customer_team_add_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentLog',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='cust_stat_agent_ct',
        ),
        migrations.AddField(
            model_name='customer',
            name='recycle_count',
            field=models.IntegerField(default=0, verbose_name='재활용 횟수'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='category_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='category_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='category_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='고객명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='region_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
