# Generated by Django 6.0.1 on 2026-02-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0012_alter_agent_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_price', models.IntegerField(default=2000)),
                ('reject_price', models.IntegerField(default=700)),
                ('invalid_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tm_settlement_prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('view_type', models.CharField(choices=[('MONTH', '월'), ('DAY', '일'), ('WEEK', '주')], default='MONTH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '지급 대기'), ('REVIEW', '검토 필요'), ('PAID', '지급 완료')], default='PENDING', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('success_count', models.IntegerField(default=0)),
                ('reject_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('calculated_amount', models.IntegerField(default=0)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='agents.agent')),
            ],
            options={
                'db_table': 'tm_settlements',
                'ordering': ['-period_start', 'agent__user__name'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='idx_settlement_period'), models.Index(fields=['status'], name='idx_settlement_status')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'period_start', 'period_end', 'view_type'), name='uniq_settlement_agent_period_view')],
            },
        ),
    ]
