# Generated by Django 6.0.1 on 2026-02-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='absence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='view_type',
            field=models.CharField(choices=[('MONTH', '월'), ('DAY', '일'), ('WEEK', '주'), ('RANGE', '기간')], default='MONTH', max_length=10),
        ),
    ]
