# Generated by Django 6.0.1 on 2026-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start', models.DateTimeField(verbose_name='통화 시작')),
                ('call_duration', models.IntegerField(default=0, verbose_name='통화 시간(초)')),
                ('result_type', models.CharField(choices=[('SUCCESS', '동의'), ('REJECT', '거절'), ('ABSENCE', '부재'), ('INVALID', '결번')], max_length=50, verbose_name='통화 결과')),
                ('is_billable', models.BooleanField(default=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/')),
            ],
            options={
                'db_table': 'tm_call_logs',
            },
        ),
    ]
