# Generated by Django 6.0.1 on 2026-02-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
    ]
