# Generated by Django 6.0.1 on 2026-02-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agent_team'),
        ('calls', '0002_alter_calllog_options'),
        ('sales', '0006_alter_salesassignment_status_delete_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='agent',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='agents.agent', verbose_name='상담원'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='assignment',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sales.salesassignment', verbose_name='영업 배정 건'),
        ),
    ]
