# Generated by Django 6.0.1 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0005_calllog_fk_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="recording_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "업로드 대기"),
                    ("UPLOADED", "업로드 완료"),
                    ("FAILED", "업로드 실패"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="recording_mime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calllog",
            name="recording_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calllog",
            name="recording_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
