# Generated by Django 6.0.1 on 2026-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agent_team'),
        ('calls', '0006_calllog_recording_meta'),
        ('sales', '0007_remove_salesassignment_tm_sales_as_agent_i_a688bb_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['assignment', 'call_start'], name='idx_call_assignment_start'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['agent', 'call_start'], name='idx_call_agent_start'),
        ),
    ]
