# Generated by Django 6.0.1 on 2026-03-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_calllog_status_before_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='callback_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='콜백 예약 일시'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='result_type',
            field=models.CharField(choices=[('SUCCESS', '동의'), ('REJECT', '거절'), ('ABSENCE', '부재'), ('INVALID', '결번'), ('CALLBACK', '콜백')], max_length=50, verbose_name='통화 결과'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status_after',
            field=models.CharField(blank=True, choices=[('NEW', '대기(미배정)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('INVALID', '결번'), ('SUCCESS', '성공(동의/계약)'), ('BUY', '구매'), ('HOLD', '보류'), ('CALLBACK', '콜백 예약')], max_length=20, null=True, verbose_name='배정 상태(변경 후)'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status_before',
            field=models.CharField(blank=True, choices=[('NEW', '대기(미배정)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('INVALID', '결번'), ('SUCCESS', '성공(동의/계약)'), ('BUY', '구매'), ('HOLD', '보류'), ('CALLBACK', '콜백 예약')], max_length=20, null=True, verbose_name='배정 상태(변경 전)'),
        ),
    ]
