# Generated by Django 6.0.1 on 2026-03-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_callback_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='상담 메모'),
        ),
    ]
