# Generated by Django 6.0.1 on 2026-02-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0012_alter_agent_team'),
        ('customers', '0013_delete_assignmentlog_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(default='SYSTEM', max_length=50)),
                ('total_assigned', models.IntegerField(default=0)),
                ('agent_count', models.IntegerField(default=0, verbose_name='참여 상담원 수')),
                ('result_detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILURE', '실패')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tm_assignment_logs',
            },
        ),
        migrations.CreateModel(
            name='SalesAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('1ST', '1차 TM'), ('2ND', '2차 영업')], default='1ST', max_length=10)),
                ('status', models.CharField(choices=[('NEW', '대기(미배정)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('ABSENCE', '부재'), ('INVALID', '결번'), ('SUCCESS', '성공(동의/계약)')], default='NEW', max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('HIGH', '상'), ('MID', '중'), ('LOW', '하')], max_length=10, null=True)),
                ('item_interested', models.CharField(blank=True, max_length=100, null=True, verbose_name='관심 아이템')),
                ('memo', models.TextField(blank=True, default='', verbose_name='상담 메모')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='agents.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customer')),
                ('parent_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assignments', to='sales.salesassignment')),
            ],
            options={
                'db_table': 'tm_sales_assignments',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start', models.DateTimeField(auto_now_add=True)),
                ('call_duration', models.IntegerField(default=0, verbose_name='통화 시간(초)')),
                ('result_type', models.CharField(max_length=50, verbose_name='통신사 결과값')),
                ('is_billable', models.BooleanField(default=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sales.salesassignment')),
            ],
            options={
                'db_table': 'tm_call_logs',
            },
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['agent', 'stage', 'status'], name='tm_sales_as_agent_i_a688bb_idx'),
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['status'], name='tm_sales_as_status_8fca8e_idx'),
        ),
    ]
