# Generated by Django 6.0.1 on 2026-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesassignment',
            name='status2',
            field=models.CharField(choices=[('BUY', '구매'), ('REFUSAL', '거절'), ('HOLD', '보류')], default='NEW', max_length=20),
        ),
    ]
