# Generated by Django 6.0.1 on 2026-02-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_salesassignment_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesassignment',
            name='status',
            field=models.CharField(choices=[('NEW', '대기(미배정)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('ABSENCE', '부재'), ('INVALID', '결번'), ('SUCCESS', '성공(동의/계약)'), ('BUY', '구매'), ('REFUSAL', '거절'), ('HOLD', '보류')], default='NEW', max_length=20),
        ),
    ]
