# Generated by Django 6.0.1 on 2026-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salespullrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesassignment',
            name='status',
            field=models.CharField(choices=[('NEW', '대기(미배정)'), ('ASSIGNED', '배정됨'), ('TRYING', '통화중'), ('REJECT', '거절'), ('INVALID', '결번'), ('SUCCESS', '성공(동의/계약)'), ('BUY', '구매'), ('HOLD', '보류')], default='NEW', max_length=20),
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
