# Generated by Django 6.0.1 on 2026-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agent_team'),
        ('customers', '0014_add_customer_status'),
        ('sales', '0006_alter_salesassignment_status_delete_calllog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesassignment',
            name='tm_sales_as_agent_i_a688bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesassignment',
            name='tm_sales_as_status_8fca8e_idx',
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['agent', 'assigned_at'], name='idx_sales_agent_date'),
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['customer', 'stage', 'status'], name='idx_sales_cust_stage_status'),
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['customer', 'assigned_at'], name='idx_sales_cust_latest_date'),
        ),
        migrations.AddIndex(
            model_name='salesassignment',
            index=models.Index(fields=['stage', 'status', 'agent', 'assigned_at'], name='idx_sales_new_leads_flow'),
        ),
    ]
