name: Deploy to Main Server

# main 브랜치에 코드가 들어올 때만 실행!
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Execute Server Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /home/gvadmin/TM_projects/gvms_TM
            
            # 서버가 다른 브랜치에 있을 수도 있으니 확실하게 main으로 변경!
            git fetch origin
            git checkout main
            
            # main 브랜치의 최신 코드를 당겨오기
            git pull origin main
            
            # 도커 재빌드 및 실행
            docker compose up -d --build